<<<<<<< HEAD
/* #undef SDL_VENDOR_INFO */
=======
/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.32.10-0-g5d2495703 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.32.10-0-g5d2495703"
#endif
>>>>>>> origin/Saturn-Next
#define SDL_REVISION_NUMBER 0

#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.32.6-0-g6510d6ccb (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.32.6-0-g6510d6ccb"
#endif
