name: macOS

on:
  push:
    branches: [ "mac-ci-test"]
  pull_request:
    branches: [ "mac-ci-test"]

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        arch:
          - runner: macos-latest
            name: aarch64
          - runner: macos-15-intel
            name: x86_64

    name: ${{ matrix.arch.name }}
    runs-on: ${{ matrix.arch.runner }}

    steps:
    - uses: actions/checkout@v6.0.1

    - name: Install dependencies
      run: brew install --formula sdl2 sdl2_mixer game-music-emu libopenmpt

    - name: Download Kart assets
      run: |
        curl -L \
        -o AssetsLinuxOnly.zip \
        "https://github.com/STJr/Kart-Public/releases/download/v1.6/AssetsLinuxOnly.zip"

    - name: Extract Kart assets
      run: |
        mkdir -p assets/installer
        unzip -q AssetsLinuxOnly.zip -d assets/installer

    - name: Configure CMake
      run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=10.11

    - name: Build SRB2Kart-Saturn
      run: ninja -C build

    - name: Upload build artifact
      uses: actions/upload-artifact@v6.0.0
      with:
        name: srb2kartsaturn-macOS-${{ matrix.arch.name }}-${{ github.sha }}
        path: build/bin
